#!/usr/bin/env python
__author__ = 'satmeet'

from sandook.app.app import App
from sandook.config.config import Config
from sandook.model.model import ModelLocal as Model
from sandook.app.sulog import SULog


def main():
    config = Config()
    sulog = SULog(config)
    appl = App(model=Model(config, sulog.logw),
               config=config,
               logw=sulog.logw)
    appl.main()


if __name__ == "__main__":
    main()
